"""chat bot migrations

Revision ID: 8c8820ef3b00
Revises: d37bc4322900
Create Date: 2025-12-09 20:23:16.447703

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '8c8820ef3b00'
down_revision: Union[str, None] = 'd37bc4322900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    if inspect(conn).has_table("chathistory"):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chathistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('chathistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chathistory_flow_id'), ['flow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chathistory_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    if not inspect(conn).has_table("chathistory"):
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chathistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chathistory_session_id'))
        batch_op.drop_index(batch_op.f('ix_chathistory_flow_id'))

    op.drop_table('chathistory')
    # ### end Alembic commands ###
